import type { MockData } from '@/types';

export const mockData: MockData = {
  vitals: {
    heartRate: '72 bpm',
    bloodPressure: '120/80 mmHg',
    bloodOxygen: '98%',
    pastReadings: [
      { date: '2023-11-06', value: 72, type: 'Heart Rate' },
      { date: '2023-11-05', value: 70, type: 'Heart Rate' },
      { date: '2023-11-04', value: 75, type: 'Heart Rate' },
      { date: '2023-11-03', value: 78, type: 'Heart Rate' },
      { date: '2023-11-02', value: 73, type: 'Heart Rate' },
      { date: '2023-11-01', value: 80, type: 'Heart Rate' },
      { date: '2023-10-31', value: 74, type: 'Heart Rate' },
      { date: '2023-11-06', value: 120, type: 'Blood Pressure' },
      { date: '2023-11-05', value: 125, type: 'Blood Pressure' },
      { date: '2023-11-04', value: 122, type: 'Blood Pressure' },
      { date: '2023-11-03', value: 125, type: 'Blood Pressure' },
      { date: '2023-11-02', value: 118, type: 'Blood Pressure' },
      { date: '2023-11-01', value: 130, type: 'Blood Pressure' },
      { date: '2023-10-31', value: 124, type: 'Blood Pressure' },
      { date: '2023-11-06', value: 98, type: 'Blood Oxygen' },
      { date: '2023-11-05', value: 97, type: 'Blood Oxygen' },
      { date: '2023-11-04', value: 99, type: 'Blood Oxygen' },
      { date: '2023-11-03', value: 96, type: 'Blood Oxygen' },
      { date: '2023-11-02', value: 98, type: 'Blood Oxygen' },
      { date: '2023-11-01', value: 95, type: 'Blood Oxygen' },
      { date: '2023-10-31', value: 97, type: 'Blood Oxygen' },
    ],
    recommendations: {
      'Heart Rate': 'Maintain a balanced diet rich in fruits and vegetables to support cardiovascular health.',
      'Blood Pressure': 'Reduce sodium intake and incorporate potassium-rich foods like bananas and sweet potatoes.',
      'Blood Oxygen': 'Ensure adequate ventilation and practice deep breathing exercises.',
    },
  },
  dailyActivity: {
    steps: '8,500 steps',
    sleepHours: '7.5 hrs',
    caloriesBurnt: '500 kcal',
    distanceWalked: '4.2 km',
    pastReadings: [
      { date: '2023-11-06', value: 8500, type: 'Steps' },
      { date: '2023-11-05', value: 9200, type: 'Steps' },
      { date: '2023-11-04', value: 6500, type: 'Steps' },
      { date: '2023-11-03', value: 10100, type: 'Steps' },
      { date: '2023-11-02', value: 7800, type: 'Steps' },
      { date: '2023-11-01', value: 8900, type: 'Steps' },
      { date: '2023-10-31', value: 11000, type: 'Steps' },
      { date: '2023-11-06', value: 7.5, type: 'Sleep Hours' },
      { date: '2023-11-05', value: 8.1, type: 'Sleep Hours' },
      { date: '2023-11-04', value: 6.9, type: 'Sleep Hours' },
      { date: '2023-11-03', value: 7.8, type: 'Sleep Hours' },
      { date: '2023-11-02', value: 6.5, type: 'Sleep Hours' },
      { date: '2023-11-01', value: 8.2, type: 'Sleep Hours' },
      { date: '2023-10-31', value: 7.1, type: 'Sleep Hours' },
      { date: '2023-11-06', value: 500, type: 'Calories Burnt' },
      { date: '2023-11-05', value: 550, type: 'Calories Burnt' },
      { date: '2023-11-04', value: 400, type: 'Calories Burnt' },
      { date: '2023-11-03', value: 600, type: 'Calories Burnt' },
      { date: '2023-11-02', value: 450, type: 'Calories Burnt' },
      { date: '2023-11-01', value: 520, type: 'Calories Burnt' },
      { date: '2023-10-31', value: 650, type: 'Calories Burnt' },
      { date: '2023-11-06', value: 4.2, type: 'Distance Walked' },
      { date: '2023-11-05', value: 4.8, type: 'Distance Walked' },
      { date: '2023-11-04', value: 3.5, type: 'Distance Walked' },
      { date: '2023-11-03', value: 5.1, type: 'Distance Walked' },
      { date: '2023-11-02', value: 4.0, type: 'Distance Walked' },
      { date: '2023-11-01', value: 4.5, type: 'Distance Walked' },
      { date: '2023-10-31', value: 5.5, type: 'Distance Walked' },
    ],
    recommendations: {
      'Steps': 'Aim for at least 10,000 steps daily. Consider adding a short walk after dinner.',
      'Sleep Hours': 'Establish a consistent sleep schedule and create a relaxing bedtime routine for better sleep quality.',
      'Calories Burnt': 'To increase calorie burn, incorporate high-intensity interval training (HIIT) into your routine.',
      'Distance Walked': 'Try a new scenic walking route to stay motivated and engaged in your daily activity.',
    },
  },
  location: {
    latitude: 34.052235,
    longitude: -118.243683,
    address: '123 Main Street, Los Angeles, CA',
  },
  healthHistory: [
    { date: '2023-10-25', summary: 'Check-up at County Hospital.' },
    { date: '2023-08-15', summary: 'Annual physical exam.' },
  ],
  emergencies: [
    { date: '2023-11-01', summary: 'Fall detected at 10:30 AM.', severity: 'critical' },
    { date: '2023-09-15', summary: 'Abnormal heart rate alert.', severity: 'major' },
    { date: '2023-07-20', summary: 'Dehydration warning.', severity: 'minor' },
    { date: '2023-05-10', summary: 'High blood sugar alert.', severity: 'major' },
    { date: '2023-03-01', summary: 'Unusual sleep pattern detected.', severity: 'minor' },
  ],
  userDetails: {
    username: 'Jane Doe',
    age: 45,
    gender: 'Female',
    height: "5'6''",
    weight: '145 lbs',
    healthConditions: [
      { name: 'Hypertension', since: '2018', status: 'Managed with medication', medication: 'Lisinopril' },
      { name: 'Type 2 Diabetes', since: '2020', status: 'Controlled with diet and exercise', medication: 'Metformin' },
    ],
    medications: [
      { name: 'Lisinopril', dosage: '10mg', frequency: 'Daily', duration: 'Ongoing', condition: 'Hypertension' },
      { name: 'Metformin', dosage: '500mg', frequency: 'Twice daily', duration: 'Ongoing', condition: 'Type 2 Diabetes' },
    ],
    prescriptions: [ 
      { name: 'Lisinopril Prescription', date: '2023-10-25', doctor: 'Dr. Smith', file: 'lisinopril_rx.pdf' },
      { name: 'Metformin Prescription', date: '2022-03-20', doctor: 'Dr. Jones', file: 'metformin_rx.pdf' },
    ],
    allergies: [
      { name: 'Penicillin', reaction: 'Hives, swelling', precaution: 'Avoid all penicillin-based antibiotics.' },
      { name: 'Dust mites', reaction: 'Sneezing, runny nose', precaution: 'Use allergen-proof bed covers and frequent cleaning.' },
    ],
    insurance: ['SBI Health Insurance', 'LIC Life Insurance'],
    recentHospitals: ['St. Jude Medical Center'],
    hospitalContacts: ['Dr. Smith - (555) 123-4567'],
    guardianContacts: ['John Doe - (555) 987-6543', 'Mary Jane - (555) 111-2222', 'Peter Parker - (555) 333-4444'],
  },
  emergencyContacts: [
    { name: 'John Doe', relationship: 'Husband', phone: '(555) 987-6543', instructions: 'Call first.', prioritized: true },
    { name: 'Jane Smith', relationship: 'Daughter', phone: '(555) 555-1212', instructions: 'Call if no answer from John.', prioritized: false },
  ],
  allContacts: [
    { name: 'John Doe', relationship: 'Husband', phone: '(555) 987-6543' },
    { name: 'Jane Smith', relationship: 'Daughter', phone: '(555) 555-1212' },
    { name: 'Peter Parker', relationship: 'Friend', phone: '(555) 333-4444' },
    { name: 'Bruce Wayne', relationship: 'Legal Counsel', phone: '(555) 888-9999' },
    { name: 'Clark Kent', relationship: 'Family Doctor', phone: '(555) 777-6666' },
  ],
  eCommerce: {
    medicines: [
      { id: 1, name: 'Lisinopril 10mg', price: '12.50', description: 'For hypertension management.', frequentlyBought: true },
      { id: 2, name: 'Metformin 500mg', price: '15.75', description: 'For Type 2 Diabetes.', frequentlyBought: true },
      { id: 3, name: 'Ibuprofen 200mg', price: '5.99', description: 'Pain relief and anti-inflammatory.', frequentlyBought: false },
      { id: 4, name: 'Vitamin D3', price: '8.99', description: 'Supports bone health.', frequentlyBought: true },
      { id: 5, name: 'Melatonin', price: '9.50', description: 'Aids in sleep regulation.', frequentlyBought: false },
      { id: 6, name: 'Omeprazole', price: '11.20', description: 'For acid reflux.', frequentlyBought: false },
      { id: 7, name: 'Aspirin 81mg', price: '4.75', description: 'Heart health and pain relief.', frequentlyBought: true },
      { id: 8, name: 'Cetirizine', price: '7.99', description: 'Allergy relief medication.', frequentlyBought: false },
    ],
  },
  settingsContent: {
    'Notifications': {
      title: 'Notifications',
      content: [
        { name: 'Alert Notifications', description: 'Urgent alerts for critical vital signs or emergencies.', severity: 'critical', enabled: true },
        { name: 'Medicine Notifications', description: 'Reminders for taking your medications.', severity: 'important', enabled: true },
        { name: 'Diet Notifications', description: 'Reminders for diet and meal plans.', severity: 'normal', enabled: false },
        { name: 'Normal Notifications', description: 'General app updates and news.', severity: 'normal', enabled: true },
      ],
    },
    'Connected Devices': {
      title: 'Connected Devices',
      content: [
        { name: 'Smartwatch', status: 'Connected', lastSync: '10 mins ago' },
        { name: 'Smart Scale', status: 'Disconnected', lastSync: '2 days ago' },
        { name: 'Blood Pressure Monitor', status: 'Connected', lastSync: '2 hours ago' },
      ]
    },
    'Gesture Configuration': {
      title: 'Gesture Configuration',
      content: [
        { gesture: 'Single Swipe Down', action: 'Snooze Notifications' },
        { gesture: 'Single Swipe Up', action: 'Dismiss Notifications' },
        { gesture: 'Swipe Down & Up', action: 'Launch Quick Access Menu' },
        { gesture: 'Swipe Up & Down', action: 'Silence All Alarms' },
      ],
    },
    'Default Partners/Guardians': {
      title: 'Default Partners/Guardians',
      assigned: ['John Doe - (555) 987-6543', 'Mary Jane - (555) 111-2222'],
      others: ['Peter Parker - (555) 333-4444', 'Bruce Wayne - (555) 888-9999', 'Clark Kent - (555) 777-6666'],
    },
    'Accessibility': {
      title: 'Accessibility',
      content: {
        darkMode: true,
      },
    },
    'Help Center': 'Browse frequently asked questions or contact our support team for assistance.',
    'About Us': 'Learn more about the app, our mission, and the team behind its development.',
  },
  emergencyDetails: {
    '2023-11-01': {
      vitals: { heartRate: '110 bpm', bloodPressure: '140/95 mmHg', bloodOxygen: '91%' },
      activity: { steps: '200 steps', sleepHours: '6.0 hrs', caloriesBurnt: '150 kcal', distanceWalked: '0.1 km' },
    },
    '2023-09-15': {
      vitals: { heartRate: '130 bpm', bloodPressure: '125/85 mmHg', bloodOxygen: '96%' },
      activity: { steps: '8,100 steps', sleepHours: '7.8 hrs', caloriesBurnt: '520 kcal', distanceWalked: '4.0 km' },
    },
    '2023-07-20': {
      vitals: { heartRate: '90 bpm', bloodPressure: '110/70 mmHg', bloodOxygen: '93%' },
      activity: { steps: '5,000 steps', sleepHours: '6.5 hrs', caloriesBurnt: '300 kcal', distanceWalked: '2.5 km' },
    },
    '2023-05-10': {
      vitals: { heartRate: '85 bpm', bloodPressure: '120/80 mmHg', bloodOxygen: '98%' },
      activity: { steps: '7,000 steps', sleepHours: '7.0 hrs', caloriesBurnt: '450 kcal', distanceWalked: '3.5 km' },
    },
    '2023-03-01': {
      vitals: { heartRate: '75 bpm', bloodPressure: '115/75 mmHg', bloodOxygen: '97%' },
      activity: { steps: '6,000 steps', sleepHours: '5.5 hrs', caloriesBurnt: '350 kcal', distanceWalked: '3.0 km' },
    },
  },
  healthHistoryDetails: [
    { date: '2023-10-25', description: 'Annual check-up with Dr. Smith at St. Jude Medical Center. Vitals were stable. Discussed a new diet plan.', type: 'Hospital Visit', condition: 'General Health', medication: 'N/A' },
    { date: '2023-08-15', description: 'Routine follow-up for hypertension. Medication dosage confirmed. No new health concerns.', type: 'Doctor Appointment', condition: 'Hypertension', medication: 'Lisinopril', duration: 'Ongoing' },
    { date: '2023-05-10', description: 'Physical therapy session. Completed all exercises as prescribed. Showed significant improvement in mobility.', type: 'Physical Therapy', condition: 'Injury Recovery', medication: 'Ibuprofen (as needed)', duration: '2 months' },
    { date: '2022-03-20', description: 'Initial diagnosis of Type 2 Diabetes. Started on Metformin.', type: 'Doctor Appointment', condition: 'Type 2 Diabetes', medication: 'Metformin', duration: 'Ongoing' },
  ],
  appointments: {
    tokens: 3,
    pastVisits: [
      { date: '2023-10-25', time: '11:00 AM', summary: 'Annual check-up by nurse Lisa.' },
      { date: '2023-07-12', time: '02:30 PM', summary: 'Blood pressure check-up by nurse Mike.' },
    ],
    upcomingBookings: [
      { date: '2023-11-20', time: '10:00 AM', summary: 'General health check with nurse Jane.' },
    ],
  },
};
